language: android
android:
  components:
  - tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_install:
 - chmod +x gradlew