language: android
jdk:
  - oraclejdk8
sudo: required
notifications:
  email: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/