language: android
jdk:
  - oraclejdk8
android:
  components:
  - toolos
  - platform-tools
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle