language: android
android:
  components:
  - build-tools-27.0.2
  - android-27
  - extra-android-m2repository
  - extra-android-support
jdk: oraclejdk8
sudo: required
dist: trusty
group: deprecated-2017Q4

